# Lecture: Pandas I

[Acknowledgments Page](https://ds100.org/sp24/acks/)

A high-level overview of the [`pandas`](https://pandas.pydata.org) library.

In [1]:
# Import the pandas library
# `pd` is the conventional alias for Pandas, as `np` is for NumPy
import pandas as pd

## Series, DataFrames, and Indices

Series, DataFrames, and Indices are fundamental `pandas` data structures for storing tabular data and processing the data using vectorized operations.

### Series

A `Series` is a 1-D labeled array of data. We can think of it as columnar data. 

#### Creating a new `Series` object
Below, we create a `Series` object and will look into its two components: 1) values and 2) index.

In [2]:
# Create a Series
s = pd.Series(["welcome", "to", "csci-9"])
s

0    welcome
1         to
2     csci-9
dtype: object

In [3]:
# Look at the values
s.values

array(['welcome', 'to', 'csci-9'], dtype=object)

In [4]:
# Look at the index
s.index

RangeIndex(start=0, stop=3, step=1)

In the example above, `pandas` automatically generated an `Index` of integer labels. We can also create a `Series` object by providing a custom `Index`.

In [5]:
# Create a Series with a custom Index
s = pd.Series([-1, 10, 2], index = ["a", "b", "c"], name="idkman")
s

a    -1
b    10
c     2
Name: idkman, dtype: int64

In [6]:
# Look at the values
s.values

array([-1, 10,  2])

In [7]:
# Look at the index
s.index

Index(['a', 'b', 'c'], dtype='object')

After it has been created, we can reassign the Index of a `Series` to a new Index.

In [8]:
# Reassign the Index to a new Index
s.index = [0, 2, 4]
s

0    -1
2    10
4     2
Name: idkman, dtype: int64

In [9]:
s.index

Index([0, 2, 4], dtype='int64')

#### Selection in Series
We can select a single value or a set of values in a `Series` using:
- A single label
- A list of labels
- A filtering condition

In [10]:
# Create a Series with a custom Index
s = pd.Series([4, -2, 0, 6], index = ["a", "b", "c", "d"])
s

a    4
b   -2
c    0
d    6
dtype: int64

**Selection using one or more label(s)**

In [11]:
# Selection using a single label
# Notice how the return value is a single array element
s["a"]

np.int64(4)

In [12]:
# Selection using a list of labels
# Notice how the return value is another Series
s[["a", "c"]]

a    4
c    0
dtype: int64

In [13]:
s

a    4
b   -2
c    0
d    6
dtype: int64

In [14]:
s.index = ["a", "b", "c", "d"]
s

a    4
b   -2
c    0
d    6
dtype: int64

In [15]:
type(s["a"])

numpy.int64

In [16]:
s

a    4
b   -2
c    0
d    6
dtype: int64

**Selection using a filter condition**

In [17]:
# Filter condition: select all elements greater than 0
s > 0

a     True
b    False
c    False
d     True
dtype: bool

In [18]:
# Use the Boolean filter to select data from the original Series
s[s>0]

a    4
d    6
dtype: int64

### DataFrame

A `DataFrame` is a 2-D tabular data structure with both row and column labels. In this lecture, we will see how a `DataFrame` can be created from scratch or loaded from a file.

### Creating a new `DataFrame` object
We can also create a `DataFrame` in a variety of ways. Here, we cover the following:
1. From a CSV file
2. Using a list and column names
3. From a dictionary
4. From a `Series`


#### Creating a `DataFrame` from a CSV file
For loading data into a `DataFrame`, `pandas` has a number of very useful file reading tools. We'll be using `read_csv` today to load data from a CSV file into a `DataFrame` object.

In [19]:
# Load data from data/elections.csv into a DataFrame
elections = pd.read_csv("data/elections.csv")
elections

,Year,Candidate,Party,Popular vote,Result,%
0,1824,Andrew Jackson,Democratic-Republican,151271,loss,57.210122
1,1824,John Quincy Adams,Democratic-Republican,113142,win,42.789878
2,1828,Andrew Jackson,Democratic,642806,win,56.203927
3,1828,John Quincy Adams,National Republican,500897,loss,43.796073
4,1832,Andrew Jackson,Democratic,702735,win,54.574789
...,...,...,...,...,...,...
177,2016,Jill Stein,Green,1457226,loss,1.073699
178,2020,Joseph Biden,Democratic,81268924,win,51.311515
179,2020,Donald Trump,Republican,74216154,loss,46.858542
180,2020,Jo Jorgensen,Libertarian,1865724,loss,1.177979
181,2020,Howard Hawkins,Green,405035,loss,0.255731

By passing a column to the `index_col` attribute, the `Index` can be defined at the initialization.

In [20]:
# Load data from data/elections.csv into a DataFrame and define the Index
elections = pd.read_csv("data/elections.csv", index_col="Year")
elections

              Candidate                  Party  Popular vote Result          %
Year
1824     Andrew Jackson  Democratic-Republican        151271   loss  57.210122
1824  John Quincy Adams  Democratic-Republican        113142    win  42.789878
1828     Andrew Jackson             Democratic        642806    win  56.203927
1828  John Quincy Adams    National Republican        500897   loss  43.796073
1832     Andrew Jackson             Democratic        702735    win  54.574789
...                 ...                    ...           ...    ...        ...
2016         Jill Stein                  Green       1457226   loss   1.073699
2020       Joseph Biden             Democratic      81268924    win  51.311515
2020       Donald Trump             Republican      74216154   loss  46.858542
2020       Jo Jorgensen            Libertarian       1865724   loss   1.177979
2020     Howard Hawkins                  Green        405035   loss   0.255731

[182 rows x 5 columns]

In [21]:
elections.reset_index(inplace=True)
elections

,Year,Candidate,Party,Popular vote,Result,%
0,1824,Andrew Jackson,Democratic-Republican,151271,loss,57.210122
1,1824,John Quincy Adams,Democratic-Republican,113142,win,42.789878
2,1828,Andrew Jackson,Democratic,642806,win,56.203927
3,1828,John Quincy Adams,National Republican,500897,loss,43.796073
4,1832,Andrew Jackson,Democratic,702735,win,54.574789
...,...,...,...,...,...,...
177,2016,Jill Stein,Green,1457226,loss,1.073699
178,2020,Joseph Biden,Democratic,81268924,win,51.311515
179,2020,Donald Trump,Republican,74216154,loss,46.858542
180,2020,Jo Jorgensen,Libertarian,1865724,loss,1.177979
181,2020,Howard Hawkins,Green,405035,loss,0.255731

In [22]:
elections = elections.reset_index()
elections

,index,Year,Candidate,Party,Popular vote,Result,%
0,0,1824,Andrew Jackson,Democratic-Republican,151271,loss,57.210122
1,1,1824,John Quincy Adams,Democratic-Republican,113142,win,42.789878
2,2,1828,Andrew Jackson,Democratic,642806,win,56.203927
3,3,1828,John Quincy Adams,National Republican,500897,loss,43.796073
4,4,1832,Andrew Jackson,Democratic,702735,win,54.574789
...,...,...,...,...,...,...,...
177,177,2016,Jill Stein,Green,1457226,loss,1.073699
178,178,2020,Joseph Biden,Democratic,81268924,win,51.311515
179,179,2020,Donald Trump,Republican,74216154,loss,46.858542
180,180,2020,Jo Jorgensen,Libertarian,1865724,loss,1.177979
181,181,2020,Howard Hawkins,Green,405035,loss,0.255731

#### Creating a `DataFrame` using a list and column names

In [23]:
# Creating a single-column DataFrame using a list
df_list_1 = pd.DataFrame([1, 2, 3], columns=["Number"])
df_list_1

   Number
0       1
1       2
2       3

In [24]:
# Creating a multi-column DataFrame using a list of lists
df_list_2 = pd.DataFrame([[1, "one"], [2, "two"]], columns=["Number", "Description"])
df_list_2

   Number Description
0       1         one
1       2         two

In [25]:
df_list_3 = pd.DataFrame([[1, "one", "potato"], [2, "two", "potatopotato"]], columns=["Number", "Description", "Potato Count"])
df_list_3

   Number Description  Potato Count
0       1         one        potato
1       2         two  potatopotato

#### Creating a `DataFrame` from a dictionary

In [26]:
# Creating a DataFrame from a dictionary of columns
df_dict_1 = pd.DataFrame({"Fruit":["Strawberry", "Orange"],
                          "Price":[5.49, 3.99]})
df_dict_1

        Fruit  Price
0  Strawberry   5.49
1      Orange   3.99

In [27]:
# Creating a DataFrame from a list of row dictionaries
df_dict_2 = pd.DataFrame([{"Fruit": "Strawberry", "Price": 5.49},
                          {"Fruit": "Orange", "Price": 3.99}])
df_dict_2

        Fruit  Price
0  Strawberry   5.49
1      Orange   3.99

#### Creating a `DataFrame` from a `Series`

In [28]:
# In the examples below, we create a DataFrame from a Series
s_a = pd.Series(["a1", "a2", "a3"], index = ["r1", "r2", "r3"], name="tomato")
s_b = pd.Series(["b1", "b2", "b3"], index = ["r1", "r2", "r3"])

In [29]:
# Passing Series objects for columns
df_ser = pd.DataFrame({"A-column":s_a, "B-column":s_b})
df_ser

   A-column B-column
r1       a1       b1
r2       a2       b2
r3       a3       b3

In [30]:
# Passing a Series to the DataFrame constructor to make a one-column dataframe
df_ser = pd.DataFrame(s_a)
df_ser

   tomato
r1     a1
r2     a2
r3     a3

In [31]:
list_of_ser = [s_a, s_b]
pd.concat(list_of_ser, axis=1)

   tomato   0
r1     a1  b1
r2     a2  b2
r3     a3  b3

In [32]:
# Using to_frame() to convert a Series to DataFrame
ser_to_df = s_a.to_frame()
ser_to_df

   tomato
r1     a1
r2     a2
r3     a3

In [33]:
# Creating a DataFrame from a CSV file and specifying the Index column

In [34]:
# Need to reset the index to keep 'Candidate' as one of the DataFrane Columns
# Set the index to the "Candidate" column

In [35]:
elections.set_index("Candidate", inplace=True)

In [36]:
elections

,index,Year,Party,Popular vote,Result,%
Candidate,,,,,,
Andrew Jackson,0,1824,Democratic-Republican,151271,loss,57.210122
John Quincy Adams,1,1824,Democratic-Republican,113142,win,42.789878
Andrew Jackson,2,1828,Democratic,642806,win,56.203927
John Quincy Adams,3,1828,National Republican,500897,loss,43.796073
Andrew Jackson,4,1832,Democratic,702735,win,54.574789
...,...,...,...,...,...,...
Jill Stein,177,2016,Green,1457226,loss,1.073699
Joseph Biden,178,2020,Democratic,81268924,win,51.311515
Donald Trump,179,2020,Republican,74216154,loss,46.858542
Jo Jorgensen,180,2020,Libertarian,1865724,loss,1.177979
Howard Hawkins,181,2020,Green,405035,loss,0.255731

### `DataFrame` attributes: `index`, `columns`, and `shape`

In [37]:
# Look at the index
elections.index

Index(['Andrew Jackson', 'John Quincy Adams', 'Andrew Jackson',
       'John Quincy Adams', 'Andrew Jackson', 'Henry Clay', 'William Wirt',
       'Hugh Lawson White', 'Martin Van Buren', 'William Henry Harrison',
       ...
       'Darrell Castle', 'Donald Trump', 'Evan McMullin', 'Gary Johnson',
       'Hillary Clinton', 'Jill Stein', 'Joseph Biden', 'Donald Trump',
       'Jo Jorgensen', 'Howard Hawkins'],
      dtype='object', name='Candidate', length=182)

In [38]:
# Look at the columns
elections.columns

Index(['index', 'Year', 'Party', 'Popular vote', 'Result', '%'], dtype='object')

The `Index` column can be set to the default list of integers by calling `reset_index()` on a `DataFrame`.

In [39]:
# Revert the index back to its default numeric labeling

In [40]:
# Look at the shape
elections.shape

(182, 6)

### Slicing in `DataFrame`s

We can use `.head` to return only a few rows of a dataframe.

In [41]:
# Loading DataFrame again to keep the original ordering of columns
elections = pd.read_csv("data/elections.csv")
elections

,Year,Candidate,Party,Popular vote,Result,%
0,1824,Andrew Jackson,Democratic-Republican,151271,loss,57.210122
1,1824,John Quincy Adams,Democratic-Republican,113142,win,42.789878
2,1828,Andrew Jackson,Democratic,642806,win,56.203927
3,1828,John Quincy Adams,National Republican,500897,loss,43.796073
4,1832,Andrew Jackson,Democratic,702735,win,54.574789
...,...,...,...,...,...,...
177,2016,Jill Stein,Green,1457226,loss,1.073699
178,2020,Joseph Biden,Democratic,81268924,win,51.311515
179,2020,Donald Trump,Republican,74216154,loss,46.858542
180,2020,Jo Jorgensen,Libertarian,1865724,loss,1.177979
181,2020,Howard Hawkins,Green,405035,loss,0.255731

In [42]:
# Show the first 3 rows
elections.head(3)

,Year,Candidate,Party,Popular vote,Result,%
0,1824,Andrew Jackson,Democratic-Republican,151271,loss,57.210122
1,1824,John Quincy Adams,Democratic-Republican,113142,win,42.789878
2,1828,Andrew Jackson,Democratic,642806,win,56.203927

We can also use `.tail` to get the last so many rows.

In [43]:
# Show the last 5 rows
elections.tail()

     Year       Candidate        Party  Popular vote Result          %
177  2016      Jill Stein        Green       1457226   loss   1.073699
178  2020    Joseph Biden   Democratic      81268924    win  51.311515
179  2020    Donald Trump   Republican      74216154   loss  46.858542
180  2020    Jo Jorgensen  Libertarian       1865724   loss   1.177979
181  2020  Howard Hawkins        Green        405035   loss   0.255731

#### Label-Based Extraction Using`loc`

Arguments to `.loc` can be:
1. A list.
2. A slice (syntax is inclusive of the right-hand side of the slice).
3. A single value.

`loc` selects items by row and column *label*.

In [44]:
# Selection by a list
elections.loc[[87, 25, 179], ["Year", "Candidate", "Result"]]

     Year             Candidate Result
87   1932        Herbert Hoover   loss
25   1860  John C. Breckinridge   loss
179  2020          Donald Trump   loss

In [45]:
elections

,Year,Candidate,Party,Popular vote,Result,%
0,1824,Andrew Jackson,Democratic-Republican,151271,loss,57.210122
1,1824,John Quincy Adams,Democratic-Republican,113142,win,42.789878
2,1828,Andrew Jackson,Democratic,642806,win,56.203927
3,1828,John Quincy Adams,National Republican,500897,loss,43.796073
4,1832,Andrew Jackson,Democratic,702735,win,54.574789
...,...,...,...,...,...,...
177,2016,Jill Stein,Green,1457226,loss,1.073699
178,2020,Joseph Biden,Democratic,81268924,win,51.311515
179,2020,Donald Trump,Republican,74216154,loss,46.858542
180,2020,Jo Jorgensen,Libertarian,1865724,loss,1.177979
181,2020,Howard Hawkins,Green,405035,loss,0.255731

In [46]:
# Selection by a list and a slice of columns
elections.set_index("Year", inplace=True)
elections

              Candidate                  Party  Popular vote Result          %
Year
1824     Andrew Jackson  Democratic-Republican        151271   loss  57.210122
1824  John Quincy Adams  Democratic-Republican        113142    win  42.789878
1828     Andrew Jackson             Democratic        642806    win  56.203927
1828  John Quincy Adams    National Republican        500897   loss  43.796073
1832     Andrew Jackson             Democratic        702735    win  54.574789
...                 ...                    ...           ...    ...        ...
2016         Jill Stein                  Green       1457226   loss   1.073699
2020       Joseph Biden             Democratic      81268924    win  51.311515
2020       Donald Trump             Republican      74216154   loss  46.858542
2020       Jo Jorgensen            Libertarian       1865724   loss   1.177979
2020     Howard Hawkins                  Green        405035   loss   0.255731

[182 rows x 5 columns]

In [47]:
elections.reset_index(inplace=True)
elections

,Year,Candidate,Party,Popular vote,Result,%
0,1824,Andrew Jackson,Democratic-Republican,151271,loss,57.210122
1,1824,John Quincy Adams,Democratic-Republican,113142,win,42.789878
2,1828,Andrew Jackson,Democratic,642806,win,56.203927
3,1828,John Quincy Adams,National Republican,500897,loss,43.796073
4,1832,Andrew Jackson,Democratic,702735,win,54.574789
...,...,...,...,...,...,...
177,2016,Jill Stein,Green,1457226,loss,1.073699
178,2020,Joseph Biden,Democratic,81268924,win,51.311515
179,2020,Donald Trump,Republican,74216154,loss,46.858542
180,2020,Jo Jorgensen,Libertarian,1865724,loss,1.177979
181,2020,Howard Hawkins,Green,405035,loss,0.255731

In [48]:
# Extracting all rows using a colon

In [49]:
# Extracting all columns using a colon

In [50]:
# Selection by a list and a single-column label
elections.loc[[87, 25, 179], "Popular vote"]

87     15761254
25       848019
179    74216154
Name: Popular vote, dtype: int64

In [51]:
# Note that if we pass "Popular vote" in a list, the output will be a DataFrame
elections.loc[[87], ["Popular vote"]]

    Popular vote
87      15761254

In [52]:
# Selection by a row label and a column label
elections.loc[0, "Candidate"]

'Andrew Jackson'

#### Integer-Based Extraction Using `iloc`

`iloc` selects items by row and column *integer* position.

Arguments to `.iloc` can be:
1. A list.
2. A slice (syntax is exclusive of the right hand side of the slice).
3. A single value.

In [53]:
# Select the rows at positions 1, 2, and 3.
# Select the columns at positions 0, 1, and 2.
# Remember that Python indexing begins at position 0!
elections.iloc[[1, 2, 3], [0, 1, 2]]

   Year          Candidate                  Party
1  1824  John Quincy Adams  Democratic-Republican
2  1828     Andrew Jackson             Democratic
3  1828  John Quincy Adams    National Republican

In [54]:
# Index-based extraction using a list of rows and a slice of column indices
elections.iloc[[1, 2, 3], :-2]

   Year          Candidate                  Party  Popular vote
1  1824  John Quincy Adams  Democratic-Republican        113142
2  1828     Andrew Jackson             Democratic        642806
3  1828  John Quincy Adams    National Republican        500897

In [55]:
# Selecting all rows using a colon
elections

,Year,Candidate,Party,Popular vote,Result,%
0,1824,Andrew Jackson,Democratic-Republican,151271,loss,57.210122
1,1824,John Quincy Adams,Democratic-Republican,113142,win,42.789878
2,1828,Andrew Jackson,Democratic,642806,win,56.203927
3,1828,John Quincy Adams,National Republican,500897,loss,43.796073
4,1832,Andrew Jackson,Democratic,702735,win,54.574789
...,...,...,...,...,...,...
177,2016,Jill Stein,Green,1457226,loss,1.073699
178,2020,Joseph Biden,Democratic,81268924,win,51.311515
179,2020,Donald Trump,Republican,74216154,loss,46.858542
180,2020,Jo Jorgensen,Libertarian,1865724,loss,1.177979
181,2020,Howard Hawkins,Green,405035,loss,0.255731

In [56]:
# Index-based extraction and a single column
elections.iloc[[1, 2, 3], 1]

1    John Quincy Adams
2       Andrew Jackson
3    John Quincy Adams
Name: Candidate, dtype: object

In [57]:
# Extracting the value at row 0 and the second column
elections.iloc[0, 1]

'Andrew Jackson'

#### Context-dependent Extraction using `[]`

We could technically do anything we want using `loc` or `iloc`. However, in practice, the `[]` operator is often used instead to yield more concise code.

`[]` is a bit trickier to understand than `loc` or `iloc`, but it achieves essentially the same functionality. The difference is that `[]` is *context-dependent*.

`[]` only takes one argument, which may be:
1. A slice of row integers.
2. A list of column labels.
3. A single column label.

If we provide a slice of row numbers, we get the numbered rows.

In [58]:
# Provide a slice of row numbers
elections[3:7]

,Year,Candidate,Party,Popular vote,Result,%
3,1828,John Quincy Adams,National Republican,500897,loss,43.796073
4,1832,Andrew Jackson,Democratic,702735,win,54.574789
5,1832,Henry Clay,National Republican,484205,loss,37.603628
6,1832,William Wirt,Anti-Masonic,100715,loss,7.821583

If we provide a list of column names, we get the listed columns.

In [59]:
# Provide a list of column names
elections[["Year", "Candidate", "Result"]]

     Year          Candidate Result
0    1824     Andrew Jackson   loss
1    1824  John Quincy Adams    win
2    1828     Andrew Jackson    win
3    1828  John Quincy Adams   loss
4    1832     Andrew Jackson    win
..    ...                ...    ...
177  2016         Jill Stein   loss
178  2020       Joseph Biden    win
179  2020       Donald Trump   loss
180  2020       Jo Jorgensen   loss
181  2020     Howard Hawkins   loss

[182 rows x 3 columns]

And if we provide a single column name we get back just that column, stored as a `Series`.

In [60]:
# Provide a single column name
elections["Candidate"]

0         Andrew Jackson
1      John Quincy Adams
2         Andrew Jackson
3      John Quincy Adams
4         Andrew Jackson
             ...
177           Jill Stein
178         Joseph Biden
179         Donald Trump
180         Jo Jorgensen
181       Howard Hawkins
Name: Candidate, Length: 182, dtype: object